--- #YAML:1.0
name:                Sphinx-Search
version:             0.22
abstract:            Sphinx search engine API Perl client
license:             ~
author:              
    - Jon Schutz <jon@jschutz.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Class::Accessor::Fast:         0
    Config:                        0
    Data::Dumper:                  0
    DBI:                           0
    Encode:                        0
    Errno:                         0
    Fcntl:                         0
    File::SearchPath:              0
    Math::BigInt:                  0
    Path::Class:                   0
    Socket:                        0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
