# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sphinx-Search
version:      0.08
version_from: lib/Sphinx/Search.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           0
    File::SearchPath:              0
    Path::Class:                   0
    Socket:                        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
